export { default as Home } from './Home/Home';
export { default as Contact } from './Contact/Contact';
export { default as Header } from './Header/Header';
export { default as Navbar } from './Navbar/Navbar';
export { default as Hero } from './Hero/Hero';
export { default as Search } from './Search/Search';
export { default as PsychologicalIssues } from './PsychologicalIssues/PsychologicalIssues';
export { default as Doctors } from './Doctors/Doctors';
export { default as Consultation } from './Consultation section/Consultation';
export { default as Footer } from './Footer/Footer';
export { default as Login } from './Login/Login';
export { default as Signup } from './Signup/Signup';
