export { default as Home } from './Home/Home';
export { default as Contact } from './Contact/Contact';
export { default as Header } from './Header/Header';
export { default as Navbar } from './Navbar/Navbar';
export { default as Hero } from './Hero/Hero';
export { default as Search } from './Search/Search';
export { default as PsychologicalIssues } from './PsychologicalIssues/PsychologicalIssues';
export { default as Doctors } from './Doctors/Doctors';
export { default as Consultation } from './Consultation section/Consultation';
export { default as Footer } from './Footer/Footer';
export { default as Login } from './Login/Login';
export { default as Signup } from './Signup/Signup';
export { default as PsychologistPage } from './PsychologistPage/PsychologistPage';
export { default as AdminDashboard } from './AdminDashboard/Dashboard';
export { default as DashboardLayout } from './DashboardLayout/DashboardLayout';
export { default as DiscussionForum } from './DiscussionForum/DiscussionForum';
export { default as DiscussionForumLayout } from './DiscussionForumLayout/DiscussionForumLayout';
