export const cardData = [
	{
		name: 'Shahzaib',
		experience: '10',
		rating: '4.5',
		degree: 'Clinical Psychology',
		specialization: 'Language Therapy',
		location: 'Lahore, Pakistan',
		clinicname: 'PsychCare Clinic',
	},
	{
		name: 'Uzair Ghaffar',
		experience: '5',
		rating: '4.8',
		degree: 'Clinical Psychology',
		specialization: 'Language Therapy',
		location: 'Lahore, Pakistan',
		clinicname: 'PsychCare Clinic',
	},
	{
		name: 'Muhammad Arslan',
		experience: '10',
		rating: '4.5',
		degree: 'Clinical Psychology',
		specialization: 'Language Therapy',
		location: 'Lahore, Pakistan',
		clinicname: 'PsychCare Clinic',
	},
	{
		name: 'Talha Amir',
		experience: '5',
		rating: '4.5',
		degree: 'Clinical Psychology',
		specialization: 'Language Therapy',
		location: 'Lahore, Pakistan',
		clinicname: 'PsychCare Clinic',
	},
	{
		name: 'Oreed Afzal',
		experience: '10',
		rating: '4.5',
		degree: 'Clinical Psychology',
		specialization: 'Language Therapy',
		location: 'Lahore, Pakistan',
		clinicname: 'PsychCare Clinic',
	},
];
